name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Django checks (without database migration)
    - name: Run Django system checks
      run: python manage.py check

    # Step 5: Run migrations
    - name: Apply migrations
      run: python manage.py migrate

    # Step 6: Run tests (if you have any)
    - name: Run tests
      run: python manage.py test
